In [2]:
%matplotlib notebook
from desdeo_emo.surrogatemodelling.EvoNN import EvoNN
from desdeo_emo.surrogatemodelling.BioGP import BioGP
from desdeo_emo.surrogatemodelling.EvoDN2 import EvoDN2
import numpy as np
import pandas as pd
from desdeo_emo.EAs.RVEA import RVEA
from desdeo_emo.EAs.NSGAIII import NSGAIII
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.


# Generating Data

Make sure that the initial dataset is in a pandas dataframe

In [3]:
X = np.random.rand(100, 3)
y = X[:, 0] * X[:, 1] + X[:, 2]
y = y.reshape(-1, 1)
data = pd.DataFrame(np.hstack((X, y)), columns=["x1", "x2", "x3", "y"])

## EvoNN model

In [4]:
model = EvoNN(pop_size=100)
model.fit(data[["x1", "x2", "x3"]], data['y'])

Plot saved as:  EvoNN.html
View the plot by opening the file in browser.
To view the plot in Jupyter Notebook, use the IFrame command.


In [5]:
y_pred = model.predict(X)

In [9]:
model.performance

{'RMSE': 2.3832945064704994e-08,
 'R^2': 0.9999999999999958,
 'AICc': -3297.9393934077316}

In [10]:
model.predict([0.1, 0.3, 0.5])

array([0.52999994])

## BioGP model

In [3]:
model2 = BioGP(pop_size=50)
model2.fit(data[["x1", "x2", "x3"]], data['y'])

Plot saved as:  evoNN.html
View the plot by opening the file in browser.
To view the plot in Jupyter Notebook, use the IFrame command.


In [4]:
model2.performance

{'RMSE': 1.3799853365199568e-16, 'R^2': 1.0}

In [9]:
model2.predict([[5,2,7]])

array([17.])

## EvoDN2 model

In [3]:
model3 = EvoDN2(training_algorithm=NSGAIII, pop_size=50)
model3.fit(data[["x1", "x2", "x3"]], data['y'])

Plot saved as:  evoNN.html
View the plot by opening the file in browser.
To view the plot in Jupyter Notebook, use the IFrame command.


In [4]:
model3.performance

{'RMSE': 1.5241947617533335e-08,
 'R^2': 0.9999999999999982,
 'Complexity': 0.008957883641851067}

In [5]:
model3.predict(np.asarray([[5,2,7]]))

array([[16.99995684]])