# Testing NUMS and NUMS+

In [1]:
# Package for plotting the results
import plotly.graph_objects as go
import numpy as np
import pandas as pd

import desdeo_emo.utilities.ReferenceVectors as ReferenceVectors
from desdeo_emo.EAs.MOEAD_NUMS import MOEA_D_NUMS
from desdeo_emo.EAs.MOEAD_NUMS_PLUS import MOEA_D_NUMS_PLUS

from desdeo_problem.testproblems.TestProblems import test_problem_builder

#function to plot results
def plot3d(data):
    fig2 = go.Figure(data=go.Scatter3d(x=data[:,0],
                                   y=data[:,1],
                                   z=data[:,2],
                                   mode="markers",
                                   marker_size=1))
    return fig2


ref_point = np.array([0.7,0.0001,0.0001])
flag = 0
roi_size= 0.1

#Problem to solve
problem = test_problem_builder(name="DTLZ1", n_of_variables=7, n_of_objectives=3)

Create the evolvers

In [2]:
int_nums = MOEA_D_NUMS(problem=problem, interact=True, n_gen_per_iter=100, roi_size=roi_size)
int_nums_plus = MOEA_D_NUMS_PLUS(problem=problem, interact=True, n_gen_per_iter=100, roi_size=roi_size, num_solutions_display=5)

Start both methods and show ideal and nadir points

In [3]:
int_nums.start()
int_nums_plus.start()

print(int_nums_plus._global_ideal_point)
print(int_nums_plus._global_nadir_point)
print(int_nums_plus._current_display_solutions)

[0.00712038 0.0085945  0.        ]
[0.50112135 0.50910915 0.45922239]
[[0.39508741 0.09100446 0.04092243]
 [0.07540842 0.25028968 0.19366757]
 [0.12323651 0.35535639 0.03904871]
 [0.04543955 0.08603121 0.3902611 ]
 [0.24062724 0.08681407 0.19787119]]


Run both methods with the initial reference point

In [4]:
pref_int_nums, plot_int_nums  = int_nums.requests()
pref_int_nums_plus, plot_int_nums_plus = int_nums_plus.requests()

pref_int_nums[2].response = pd.DataFrame([ref_point], columns=pref_int_nums[2].content['dimensions_data'].columns)
pref_int_nums_plus[2].response = pd.DataFrame([ref_point], columns=pref_int_nums_plus[2].content['dimensions_data'].columns)

pref_int_nums, plot_int_nums = int_nums.iterate(pref_int_nums[2])
pref_int_nums_plus, plot_int_nums_plus  = int_nums_plus.iterate(pref_int_nums_plus[2])

fig_nums = plot3d(int_nums.population.objectives)
fig_nums_plus = plot3d(int_nums_plus.population.objectives)

fig_nums

ValidationError: Reference point should be worse than or equal to the ideal point
The following columns have problematic values: [('f2',)]

In [ ]:
fig_nums_plus