# Transforming an a priori method into an interactive one
Examples fot the PPSN article

In [1]:
# Package for plotting the results
import plotly.graph_objects as go

# Package to create the Problem object
from desdeo_problem.testproblems.TestProblems import test_problem_builder

# Packages for using MOEA/D and the available scalarization functions
from desdeo_emo.EAs.MOEAD_NUMS_PLUS import MOEA_D_NUMS_PLUS
from desdeo_emo.EAs.MOEAD import MOEA_D
from desdeo_problem import variable_builder, ScalarObjective, VectorObjective, MOProblem
from desdeo_problem.problem import Variable
import numpy as np
import pandas as pd

# create the problem
def f_1(x):
    x = np.atleast_2d(x)
    return (
        1640.2823
        + 2.3573285 * x[:, 0]
        + 2.3220035 * x[:, 1]
        + 4.5688768 * x[:, 2]
        + 7.7213633 * x[:, 3]
        + 4.4559504 * x[:, 4]
    )


def f_2(x):
    x = np.atleast_2d(x)
    return (
        6.5856
        + 1.15 * x[:, 0]
        - 1.0427 * x[:, 1]
        + 0.9738 * x[:, 2]
        + 0.8364 * x[:, 3]
        - 0.3695 * x[:, 0] * x[:, 3]
        + 0.0861 * x[:, 0] * x[:, 4]
        + 0.3628 * x[:, 1] * x[:, 3]
        - 0.1106 * x[:, 0] ** 2
        - 0.3437 * x[:, 2] ** 2
        + 0.1764 * x[:, 3] ** 2
    )

def f_3(x):
    x = np.atleast_2d(x)
    return (
        -0.0551
        + 0.0181 * x[:, 0]
        + 0.1024 * x[:, 1]
        + 0.0421 * x[:, 2]
        - 0.0073 * x[:, 0] * x[:, 1]
        + 0.024 * x[:, 1] * x[:, 2]
        - 0.0118 * x[:, 1] * x[:, 3]
        - 0.0204 * x[:, 2] * x[:, 3]
        - 0.008 * x[:, 2] * x[:, 4]
        - 0.0241 * x[:, 1] ** 2
        + 0.0109 * x[:, 3] ** 2
    )
f1 = ScalarObjective(name="f1", evaluator=f_1)
f2 = ScalarObjective(name="f2", evaluator=f_2)
f3 = ScalarObjective(name="f3", evaluator=f_3)

x_1 = Variable("x_1", 2.0, 1.0, 3.0)
x_2 = Variable("x_2", 2.0, 1.0, 3.0)
x_3 = Variable("x_3", 2.0, 1.0, 3.0)
x_4 = Variable("x_4", 2.0, 1.0, 3.0)
x_5 = Variable("x_5", 2.0, 1.0, 3.0)
variables = [x_1, x_2, x_3, x_4, x_5]
problem = MOProblem(variables=variables, objectives=[f1, f2, f3])

solutions_display = 5

def plot_complete(data, pareto_front):
    trace1 = go.Scatter3d(x=pareto_front[:,0],y=pareto_front[:,1],z=pareto_front[:,2],mode='markers',marker_size=1)
    trace2 = go.Scatter3d(x=data[:,0],y=data[:,1],z=data[:,2],mode='markers',marker_size=1)
    fig = go.Figure(data= [trace1,trace2])
    return fig




def plot_results_scatter(data):
    fig2 = go.Figure(data=go.Scatter3d(x=data[:,0],
                                   y=data[:,1],
                                   z=data[:,2],
                                   mode="markers",
                                   marker_size=1))
    return fig2



Create the object and run the initialization step

In [2]:
int_nums_plus = MOEA_D_NUMS_PLUS(problem=problem, interact=True, n_gen_per_iter=100, roi_size=0.3, num_solutions_display=5)


int_nums_plus.start()

print("Ideal point", int_nums_plus._ideal_point)
#print("Nadir point", int_nums_plus._nadir_point)

front = np.copy(int_nums_plus.population.objectives)
fig = plot_results_scatter(int_nums_plus.population.objectives)
fig

Ideal point [1.66170782e+03 7.37095942e+00 4.80853637e-02]


Ask for preference information. Then, run the a priori algorithm

In [3]:
reference_point = [int_nums_plus._ideal_point[0],int_nums_plus._ideal_point[1],int_nums_plus._ideal_point[2]]

pref_int_nums_plus, plot_int_nums_plus = int_nums_plus.requests()
pref_int_nums_plus[2].response = pd.DataFrame([reference_point], columns=pref_int_nums_plus[2].content['dimensions_data'].columns)
pref_int_nums_plus, plot_int_nums_plus  = int_nums_plus.iterate(pref_int_nums_plus[2])
print(int_nums_plus._current_display_solutions)
print(int_nums_plus._reference_point_list)

fig = plot_complete(int_nums_plus.population.objectives,front)
fig


/home/giomara/PPSN2022/desdeo-emo/desdeo_emo/utilities/ReferenceVectors.py:443: RuntimeWarning:

invalid value encountered in true_divide



[[1.66232288e+03 8.12450595e+00 8.47636638e-02]
 [1.66195481e+03 8.23227998e+00 7.68137107e-02]
 [1.66422762e+03 7.56678425e+00 1.06553620e-01]
 [1.66331806e+03 7.83310989e+00 1.00194367e-01]
 [1.66277957e+03 7.99078510e+00 9.29440041e-02]]
[[1.66170782e+03 7.37095942e+00 4.80853637e-02]]


Select reference point closer to the front

In [4]:
reference_point = [1661.9,8,1]
pref_int_nums_plus, plot_int_nums_plus = int_nums_plus.requests()
pref_int_nums_plus[2].response = pd.DataFrame([reference_point], columns=pref_int_nums_plus[2].content['dimensions_data'].columns)
pref_int_nums_plus, plot_int_nums_plus  = int_nums_plus.iterate(pref_int_nums_plus[2])
print(int_nums_plus._current_display_solutions)
print(int_nums_plus._reference_point_list)

fig = plot_complete(int_nums_plus.population.objectives,front)
fig

[[1.66207450e+03 8.19723550e+00 7.95316465e-02]
 [1.66194923e+03 8.23391370e+00 7.66838807e-02]
 [1.66213662e+03 8.17904613e+00 8.08918739e-02]
 [1.66202570e+03 8.21152370e+00 7.84389621e-02]
 [1.66198656e+03 8.22298344e+00 7.75471992e-02]]
[[1.66170782e+03 7.37095942e+00 4.80853637e-02]
 [1.66190000e+03 8.00000000e+00 1.00000000e+00]]


Change direction

In [5]:
reference_point = [1665,7.4,0.1]
pref_int_nums_plus, plot_int_nums_plus = int_nums_plus.requests()
pref_int_nums_plus[2].response = pd.DataFrame([reference_point], columns=pref_int_nums_plus[2].content['dimensions_data'].columns)
pref_int_nums_plus, plot_int_nums_plus  = int_nums_plus.iterate(pref_int_nums_plus[2])
print(int_nums_plus._current_display_solutions)
print(int_nums_plus._reference_point_list)

fig = plot_complete(int_nums_plus.population.objectives,front)
fig

[[1.66392952e+03 7.65407021e+00 1.05284172e-01]
 [1.66504622e+03 7.32709367e+00 1.05953609e-01]
 [1.66280604e+03 7.98303253e+00 9.33610840e-02]
 [1.66337300e+03 7.81702297e+00 1.00788357e-01]
 [1.66441512e+03 7.51188256e+00 1.06945106e-01]]
[[1.66170782e+03 7.37095942e+00 4.80853637e-02]
 [1.66190000e+03 8.00000000e+00 1.00000000e+00]
 [1.66500000e+03 7.40000000e+00 1.00000000e-01]]


reutilize previous

In [6]:
#Measure ASF with archive
def euclid_dist(t1, t2):
    return np.sqrt(((t1-t2)**2).sum(axis = 1))

distance = euclid_dist(int_nums_plus._reference_point_list[1],int_nums_plus._archive_objectives)
idx = np.argpartition(distance, int_nums_plus.num_solutions_display)[:int_nums_plus.num_solutions_display]

#print(distance)
#print(int_nums_plus._reference_point_list)
#print(idx)

idx_change = np.array(int_nums_plus._archive_indexes[idx]).astype(int)
#print(idx_change)
#print(int_nums_plus._archive_variables[idx])
#print(int_nums_plus._archive_indexes[idx])

#replace in the population for the next generation
int_nums_plus.population.individuals[idx_change] = int_nums_plus._archive_variables[idx]

Reduce spread size

In [7]:
int_nums_plus.roi_size = 0.2

reference_point = int_nums_plus._reference_point_list[1]
pref_int_nums_plus, plot_int_nums_plus = int_nums_plus.requests()
pref_int_nums_plus[2].response = pd.DataFrame([reference_point], columns=pref_int_nums_plus[2].content['dimensions_data'].columns)
pref_int_nums_plus, plot_int_nums_plus  = int_nums_plus.iterate(pref_int_nums_plus[2])
print(int_nums_plus._current_display_solutions)
print(int_nums_plus._reference_point_list)

fig = plot_complete(int_nums_plus.population.objectives,front)
fig

[[1.66202156e+03 8.21273524e+00 7.83453306e-02]
 [1.66214787e+03 8.17575198e+00 8.11345253e-02]
 [1.66210029e+03 8.18968184e+00 8.01007087e-02]
 [1.66198761e+03 8.22267650e+00 7.75712632e-02]
 [1.66205562e+03 8.20276151e+00 7.91115713e-02]]
[[1.66170782e+03 7.37095942e+00 4.80853637e-02]
 [1.66190000e+03 8.00000000e+00 1.00000000e+00]
 [1.66500000e+03 7.40000000e+00 1.00000000e-01]
 [1.66190000e+03 8.00000000e+00 1.00000000e+00]]


In [8]:
int_nums_plus.roi_size = 0.1

reference_point = int_nums_plus._reference_point_list[1]
pref_int_nums_plus, plot_int_nums_plus = int_nums_plus.requests()
pref_int_nums_plus[2].response = pd.DataFrame([reference_point], columns=pref_int_nums_plus[2].content['dimensions_data'].columns)
pref_int_nums_plus, plot_int_nums_plus  = int_nums_plus.iterate(pref_int_nums_plus[2])
print(int_nums_plus._current_display_solutions)
print(int_nums_plus._reference_point_list)

fig = plot_complete(int_nums_plus.population.objectives,front)
fig

[[1.66201391e+03 8.21497459e+00 7.81718652e-02]
 [1.66204746e+03 8.20515166e+00 7.89288912e-02]
 [1.66202937e+03 8.21044731e+00 7.85220198e-02]
 [1.66206975e+03 8.19862606e+00 7.94262391e-02]
 [1.66199911e+03 8.21930906e+00 7.78346204e-02]]
[[1.66170782e+03 7.37095942e+00 4.80853637e-02]
 [1.66190000e+03 8.00000000e+00 1.00000000e+00]
 [1.66500000e+03 7.40000000e+00 1.00000000e-01]
 [1.66190000e+03 8.00000000e+00 1.00000000e+00]
 [1.66190000e+03 8.00000000e+00 1.00000000e+00]]


In [9]:
trace = go.Parcoords(int_nums_plus.population.objectives)

fig = go.Figure(data=[trace])
fig

ValueError: The first argument to the plotly.graph_objs.Parcoords 
constructor must be a dict or 
an instance of :class:`plotly.graph_objs.Parcoords`